project:
  type: book

book:
  title: "Systems Immunology Workshops"
  author: "Center for Computational Biomedicine"
  date: today
  chapters:
    - index.qmd
    - part: preWork/pre_work.qmd
      chapters:
        - preWork/install.qmd
        - preWork/rstudio.qmd
    - part: session1/session1.qmd
      chapters:
        - session1/types.qmd
        - session1/prob.qmd
        - session1/hypo_tests.qmd
        - session1/factors.qmd
        - session1/choosing_tests.qmd
        - session1/pSet1.qmd
    - part: session2/session2.qmd
      chapters:
        - session2/packages.qmd
        - session2/loading_functions.qmd
        - session2/pvals.qmd
        - session2/mult.qmd
        - session2/making_functions.qmd
        - session2/session2problems.qmd
        - session2/pSet2.qmd
    - part: session3/session3.qmd
      chapters:
        - session3/count_data1.qmd
        - session3/wrangling.qmd
        - session3/matching_reordering.qmd
        - session3/tidyverse.qmd
        - session3/pSet3.qmd
    - part: session4/session4.qmd
      chapters:
        - session4/linear_models.qmd
        - session4/ggplot.qmd
        - session4/exporting.qmd
        - session4/other_plots.qmd
        - session4/pSet4.qmd
    - part: resources/resources.qmd
      chapters:
        - resources/git.qmd
     # - part: session5/session5.qmd
     #   chapters:
     #     - session5/summarized_experiment.qmd
     #     - session5/de_analysis.qmd
     #     - session5/enrichment_analysis.qmd
     #     - resources/literature.qmd
     #     - resources/tutorials.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

